"""Baseline migration: create all five tables.

Revision ID: 001
Revises: None
Create Date: 2026-03-30

Manual migration (not autogenerated) that creates the full baseline schema.
Tables: companies, users, cnab_files, payments, audit_logs.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all five database tables."""

    op.create_table(
        'companies',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('cnpj', sa.String(14), nullable=False),
        sa.Column('agency', sa.String(5), nullable=False),
        sa.Column('account', sa.String(12), nullable=False),
        sa.Column('dac', sa.String(1), nullable=False),
        sa.Column('name', sa.String(30), nullable=False),
        sa.Column('address', sa.String(30), nullable=False, server_default=''),
        sa.Column('address_number', sa.String(5), nullable=False, server_default=''),
        sa.Column('complement', sa.String(15), nullable=False, server_default=''),
        sa.Column('city', sa.String(20), nullable=False, server_default=''),
        sa.Column('cep', sa.String(8), nullable=False, server_default=''),
        sa.Column('state', sa.String(2), nullable=False, server_default=''),
        sa.Column('tipo_pagamento', sa.Integer(), nullable=False, server_default='20'),
        sa.Column('vtex_app_key_encrypted', sa.Text(), nullable=True),
        sa.Column('vtex_app_token_encrypted', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('password_hash', sa.String(256), nullable=False, server_default=''),
        sa.Column('role', sa.String(10), nullable=False, server_default='user'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('display_name', sa.String(100), nullable=False, server_default=''),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )

    op.create_table(
        'cnab_files',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('filename', sa.String(255), nullable=False),
        sa.Column('file_content', sa.LargeBinary(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='Criado'),
        sa.Column('row_count', sa.Integer(), nullable=False),
        sa.Column('total_value_cents', sa.Integer(), nullable=False),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('transmitted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id']),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'payments',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('cnab_file_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(30), nullable=False),
        sa.Column('document', sa.String(14), nullable=False),
        sa.Column('pix_key', sa.String(100), nullable=False),
        sa.Column('pix_key_type', sa.String(2), nullable=False),
        sa.Column('value_cents', sa.Integer(), nullable=False),
        sa.Column('reference_id', sa.String(50), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='Pendente'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['cnab_file_id'], ['cnab_files.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('target_type', sa.String(50), nullable=True),
        sa.Column('target_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Drop all five tables in reverse dependency order."""
    op.drop_table('audit_logs')
    op.drop_table('payments')
    op.drop_table('cnab_files')
    op.drop_table('users')
    op.drop_table('companies')
